### ISSUE TITLE
Fingerprint not working on Infinix Zero 30 4g

### ISSUE THREAD

**Issue by rV4nxZ** [ItsLynix/RisingTreble#4]
Title self explanatory.
[my_loglmfao.log](https://github.com/user-attachments/files/15749290/my_loglmfao.log)

**Comment by ItsLynix** [comment]
Device uses under display sensor, I am not dedicated to writing brand new feature support for a device.

Someone like PHH might do so as he did with Samsung and Asus if you give him a free phone, but I don't have the skills to do that. Sorry.
